{{- if and (not .Values.auth.existingSecret) .Values.auth.username .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "explo.fullname" . }}-auth
  labels:
    {{- include "explo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.usernameKey }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
